INSERT INTO FOOD
(ID, VERSION, NAME, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 0, 'BROCCOLI', 500, 25, 25, 50);

INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 2);