INSERT INTO USERS (VERSION, USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES (0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');

INSERT INTO USERS (VERSION, USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES (0, 'laci', 'laci@gmail.com', '123', 'USER');

INSERT INTO USERS (VERSION, USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES (0, 'marcell', 'marcell@gmail.com', 'xaxaxa', 'USER');

INSERT INTO USERS (VERSION, USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES (0, 'yo', 'yomama@sofat.com', 'kappa123', 'USER');

INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'broccoli', 100, 70, 80, 16, 4);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'carrot', 100, 41, 89, 6, 5);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'potato', 100, 93, 92, 7, 1);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'rice', 100, 130, 90, 8, 2);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'soychunk', 100, 333, 40, 60, 0);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'sweet potato', 100, 90, 93, 6, 1);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'spinach', 100, 23, 56, 30, 14);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'lentil', 100, 116, 70, 27, 3);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'beans', 100, 139, 74, 24, 2);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'flax seed', 100, 534, 22, 12, 66);


INSERT INTO RECIPE (VERSION, USERNAME, NAME, DETAILS)
VALUES (0, 'test','Brokkolis kaposzta', 'Test');
