INSERT INTO USERS (VERSION, USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES (0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');

INSERT INTO USERS (VERSION, USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES (0, 'laci', 'laci@gmail.com', '123', 'USER');

INSERT INTO USERS (VERSION, USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES (0, 'marcell', 'marcell@gmail.com', 'xaxaxa', 'USER');

INSERT INTO USERS (VERSION, USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES (0, 'yo', 'yomama@sofat.com', 'kappa123', 'USER');

INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'broccoli', 100, 70, 80, 16, 4);
INSERT INTO FOODS (VERSION, NAME, AMOUNT, CALORIE, CARBOHYDRATE, PROTEIN, FAT)
VALUES (0, 'bread', 100, 500, 60, 16, 24);